version: '2'
services:
    server:
        build: .
        restart: always
        environment:
            VARNISH_CONFIG: /etc/varnish/default.vcl
            CACHE_SIZE: 512m
            VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
            VARNISH_PORT: 80
            BACKEND_HOST: localhost
            BACKEND_PORT: 8080

    balancer:
        image: dockercloud/haproxy:latest
        restart: always
        ports:
            - 9999:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - server
        depends_on:
            - server
