version: '2'
services:
    server:
        build: .
        restart: always
        environment:
            SYMFONY_ENV: dev
            CACHE_SIZE: 512m
            BACKEND_HOST: localhost
            BACKEND_PORT: 8080

    balancer:
        image: dockercloud/haproxy:latest
        restart: always
        ports:
            - 9999:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - server
        depends_on:
            - server
