version: '2'
services:
    server:
        build: .
        restart: always

    balancer:
        image: dockercloud/haproxy:latest
        restart: always
        ports:
            - 9999:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - server
        depends_on:
            - server
