app:
    base_url: 'abc'
    routes:
        - { path: '/{a}/{b}', controller: 'Bisnis:Home@index', methods: ['GET'] }
    template:
        path: '/var/views'
        cache_dir: '/var/cache'
# Aktifkan jika ingin mencoba kerja event listenernya
#    event_listeners:
#        - { event: 'kernel.request', class: 'Bisnis\EventListener\TestListener', method: 'test' }