app:
    api:
        base_url: 'http://10.5.5.206:8000/api/'
#        base_url: 'https://82600595.ngrok.io/api/'
        api_key: '61d757f800a5f35159c5143215158fe15ed036ad'
        param_key: 'api_key'
    template:
        path: 'views'
        cache_dir: 'caches'