app:
    api:
        base_url: 'http://10.5.5.206:8000/api/'
#        base_url: 'https://82600595.ngrok.io/api/'
        api_key: '2c5c73d28375176046344bbc018e408890d67c2c'
        param_key: 'api_key'
    template:
        path: 'views'
        cache_dir: 'caches'