app:
    api:
#        base_url: 'http://10.1.1.197:8000/api/'
#        api_key: '29913925d7c6bf9c8f1f4d3ca58f098382975c18'
        base_url: 'http://10.5.5.206:8000/api/'
        api_key: 'e10db52336fc4a71e4b36bd8acb39209f132c7e8'
        param_key: 'api_key'
    http: ~
    template:
        path: 'views'
        cache_dir: 'caches'