app:
    middlewares:
        - { class: 'Bisnis\Middleware\SecurityMiddleware' }
        - { class: 'Bisnis\Middleware\FilterMiddleware', parameters: [['Bisnis\Filter\BooleanFilter', 'Bisnis\Filter\NullFilter', 'Bisnis\Filter\FloatFilter', 'Bisnis\Filter\StringFilter', 'Bisnis\Filter\IntFilter']] }