app:
    middlewares:
        - { class: 'Bisnis\Middleware\SecurityMiddleware' }
        - { class: 'Bisnis\Middleware\SecurityMiddleware', parameters: ['Bisnis\Filter\BooleanFilter', 'Bisnis\Filter\NullFilter'] }