app:
    routes:
        #Index
        - { path: '/', controller: 'Bisnis:Home@index', methods: ['GET'] }

        #API
        - { path: '/api', controller: 'Bisnis:Api@call', methods: ['POST'] }
        - { path: '/api/search', controller: 'Bisnis:Api@search', methods: ['POST'] }
        - { path: '/api/roles', controller: 'Bisnis:Api@getRole', methods: ['POST'] }
        - { path: '/api/menus', controller: 'Bisnis:Api@menus', methods: ['POST'] }

        #Administration
        - { path: '/clients', controller: 'Bisnis:Clients@index', methods: ['GET'] }
        - { path: '/modules', controller: 'Bisnis:Modules@index', methods: ['GET'] }
        - { path: '/users', controller: 'Bisnis:Users@index', methods: ['GET'] }
        - { path: '/settings', controller: 'Bisnis:Settings@index', methods: ['GET'] }
        - { path: '/user-activities', controller: 'Bisnis:UserActivities@index', methods: ['GET'] }

        #Profile
        - { path: '/profile', controller: 'Bisnis:Profile@index', methods: ['GET'] }

        #Login
        - { path: '/login', controller: 'Bisnis:Login@index', methods: ['GET'] }
        - { path: '/login_check', controller: 'Bisnis:Login@processLogin', methods: ['POST'] }
        - { path: '/logout', controller: 'Bisnis:Login@logout', methods: ['PUT'] }