app:
    routes:
        #Index
        - { path: '/', controller: 'Bisnis:Home@index', methods: ['GET'] }

        #API
        - { path: '/api/images/{path}', controller: 'Bisnis:Api@callImage', methods: ['GET'], requirements: {'path': '.+' } }
        - { path: '/api', controller: 'Bisnis:Api@call', methods: ['POST'] }
        - { path: '/api/search', controller: 'Bisnis:Api@search', methods: ['POST'] }
        - { path: '/api/roles', controller: 'Bisnis:Api@getRole', methods: ['POST'] }
        - { path: '/api/menus', controller: 'Bisnis:Api@menus', methods: ['POST'] }
        - { path: '/api/adv-spec-detail', controller: 'Bisnis:Api@advDetail', methods: ['POST'] }

        #Profile
        - { path: '/profile', controller: 'Bisnis:Profile@index', methods: ['GET'] }

        #Login
        - { path: '/login', controller: 'Bisnis:Login@index', methods: ['GET'] }
        - { path: '/login_check', controller: 'Bisnis:Login@processLogin', methods: ['POST'] }
        - { path: '/logout', controller: 'Bisnis:Login@logout', methods: ['PUT', 'GET'] }

        #Administration
        - { path: '/clients', controller: 'Bisnis:Clients@index', methods: ['GET'] }
        - { path: '/modules', controller: 'Bisnis:Modules@index', methods: ['GET'] }
        - { path: '/users', controller: 'Bisnis:Users@index', methods: ['GET'] }
        - { path: '/settings', controller: 'Bisnis:Settings@index', methods: ['GET'] }
        - { path: '/user-activities', controller: 'Bisnis:UserActivities@index', methods: ['GET'] }
        - { path: '/cities', controller: 'Bisnis:Cities@index', methods: ['GET'] }
        - { path: '/banks', controller: 'Bisnis:Banks@index', methods: ['GET'] }
        - { path: '/representatives', controller: 'Bisnis:Representatives@index', methods: ['GET'] }
        - { path: '/services', controller: 'Bisnis:Services@index', methods: ['GET'] }

        #Advertising
        #Master
        - { path: '/advertising/ads', controller: 'Bisnis:AdvertisingAds@index', methods: ['GET'] }
        - { path: '/advertising/categories', controller: 'Bisnis:AdvertisingCategories@index', methods: ['GET'] }
        - { path: '/advertising/emiten', controller: 'Bisnis:AdvertisingEmiten@index', methods: ['GET'] }
        - { path: '/advertising/sektor', controller: 'Bisnis:AdvertisingSektor@index', methods: ['GET'] }
        - { path: '/advertising/sub-sektor', controller: 'Bisnis:AdvertisingSubSektor@index', methods: ['GET'] }
        - { path: '/advertising/customers', controller: 'Bisnis:AdvertisingCustomers@index', methods: ['GET'] }
        - { path: '/advertising/layouts', controller: 'Bisnis:AdvertisingLayouts@index', methods: ['GET'] }
        - { path: '/advertising/payment-methods', controller: 'Bisnis:AdvertisingPaymentMethods@index', methods: ['GET'] }
        - { path: '/advertising/positions', controller: 'Bisnis:AdvertisingPositions@index', methods: ['GET'] }
        - { path: '/advertising/specifications', controller: 'Bisnis:AdvertisingSpecifications@index', methods: ['GET'] }
        - { path: '/advertising/specification-details', controller: 'Bisnis:AdvertisingSpecificationDetails@index', methods: ['GET'] }
        - { path: '/advertising/types', controller: 'Bisnis:AdvertisingTypes@index', methods: ['GET'] }
        - { path: '/advertising/prices', controller: 'Bisnis:AdvertisingPrices@index', methods: ['GET'] }
        - { path: '/advertising/account-executives', controller: 'Bisnis:AdvertisingAccountExecutives@index', methods: ['GET'] }
        - { path: '/advertising/media', controller: 'Bisnis:AdvertisingMedia@index', methods: ['GET'] }

        - { path: '/advertising/orders', controller: 'Bisnis:AdvertisingOrders@index', methods: ['GET'] }
        - { path: '/advertising/orders/new', controller: 'Bisnis:AdvertisingOrders@new', methods: ['GET'] }
        - { path: '/advertising/orders/{id}', controller: 'Bisnis:AdvertisingOrders@detail', methods: ['GET'] }
        - { path: '/advertising/orders/publish-ads', controller: 'Bisnis:AdvertisingOrders@publishAds', methods: ['POST'] }
        - { path: '/advertising/orders/publish-ads/update', controller: 'Bisnis:AdvertisingOrders@updatePublishAds', methods: ['POST'] }

        #Billing
        - { path: '/billing/areas', controller: 'Bisnis:BillingAreas@index', methods: ['GET'] }
        - { path: '/billing/groups', controller: 'Bisnis:BillingGroups@index', methods: ['GET'] }
        - { path: '/billing/identities', controller: 'Bisnis:BillingIdentities@index', methods: ['GET'] }
        - { path: '/billing/payment-methods', controller: 'Bisnis:BillingPaymentMethods@index', methods: ['GET'] }

         #Helpdesk
        - { path: '/helpdesk/categories', controller: 'Bisnis:HelpdeskCategories@index', methods: ['GET'] }
        - { path: '/helpdesk/notifications', controller: 'Bisnis:HelpdeskNotifications@index', methods: ['GET'] }
        - { path: '/helpdesk/staffs', controller: 'Bisnis:HelpdeskStaffs@index', methods: ['GET'] }
        - { path: '/helpdesk/ticket-responses', controller: 'Bisnis:HelpdeskTicketResponses@index', methods: ['GET'] }
        - { path: '/helpdesk/tickets', controller: 'Bisnis:HelpdeskTickets@index', methods: ['GET'] }
        - { path: '/helpdesk/clients', controller: 'Bisnis:HelpdeskClients@index', methods: ['GET'] }
        - { path: '/helpdesk/my-tickets', controller: 'Bisnis:HelpdeskMyTickets@index', methods: ['GET'] }

        #jangan di hapus,
        - { path: '/dummy', controller: 'Bisnis:Dummy@index', methods: ['GET'] }